[workspace]
authors = ["lee-jin-gyu96 <jin.gyu.lee.96@gmail.com>"]
channels = ["nvidia", "pytorch", "conda-forge", "pyg", "openeye"]
name = "MolFinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.8"
pandas = ">=2.0.3,<3"
numpy = ">=1.24.4,<2"
matplotlib = ">=3.7.3,<4"
rdkit = ">=2022.9.1,<2023"
pip = ">=24.3.1,<25"

[feature.stella.dependencies]
cairosvg = ">=2.7.1,<3"
loguru = ">=0.7.2,<0.8"
ipython = ">=8.12.2,<9"
openeye-toolkits = ">=2023.1.0,<2024"
svgutils = ">=0.3.4,<0.4"
tqdm = ">=4.67.1,<5"
pytorch = { version = ">=2", channel = "pytorch" }
torchvision = { version = ">=0.20.0,<0.21", channel = "pytorch" }
torchaudio = { version = ">=2.4.1,<3", channel = "pytorch" }
pyg = { version = ">=2.6.1,<3", channel = "pyg" }
pytorch-scatter = { version = ">=2.1.2,<3", channel = "pyg" }
pytorch-sparse = { version = ">=0.6.18,<0.7", channel = "pyg" }
lightning = ">=2.3.3,<3"
hydra-core = ">=1.3.2,<2"
hydra-colorlog = ">=1.2.0,<2"
python-dotenv = ">=1.0.1,<2"
rich = ">=13.9.4,<14"
pytdc = ">=0.3.8,<0.4"

[feature.stella.pypi-dependencies]
dimorphite-dl = ">=1.3.2, <2"
pkasolver = { git = "https://github.com/Standigm/pkasolver" }

[feature.stella.tasks]
ligprep = { cmd = ["python", "-m", "pip", "install", "external/ligprep"] }
qip = { cmd = ["python", "-m", "pip", "install", "external/QIP"] }
ext = { cmd = ["echo", "'done'"], depends-on = ["ligprep", "qip"] }

# Seems like all solve-groups depend on default
# [feature.py37.dependencies]
# python = "==3.7"
# pandas = ">=1.3.5,<2"
# numpy = ">=1.21.6,<2"
# matplotlib = ">=3.3.2,<4"
# rdkit = ">=2019.9.3"

[environments]
stella = { features = ["stella"] }
# py37 = { features = ["py37"], solve-group = "py37" }
