[workspace]
authors = ["lee-jin-gyu96 <jin.gyu.lee.96@gmail.com>"]
channels = ["pytorch", "conda-forge", "pyg", "openeye"]
name = "MolFinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.7"
pandas = ">=1.3.5,<2"
numpy = ">=1.21.6,<2"
matplotlib = ">=3.3.2,<4"
rdkit = ">=2019.9.3"

[feature.stella.dependencies]
cairosvg = ">=2.7.1,<3"
loguru = ">=0.6.0,<0.7"
ipython = ">=7.33.0,<8"
openeye-toolkits = ">=2023.1.0,<2024"
svgutils = ">=0.3.4,<0.4"
tqdm = ">=4.67.1,<5"
pytorch = { version = "<=2.1.2", channel = "pytorch" }
pytorch-scatter = ">=2.1.1,<3"
pytorch-sparse = ">=0.6.17,<0.7"

[feature.stella.pypi-dependencies]
dimorphite-dl = ">=1.3.2, <2"
pkasolver = { git = "https://github.com/Standigm/pkasolver" }

[feature.stella.tasks]
ligprep = { cmd = ["pip", "install", "external/ligprep"] }
qip = { cmd = ["pip", "install", "external/QIP"] }
ext = { cmd = ["echo", "'done'"], depends-on = ["ligprep", "qip"] }

[environments]
stella = { features = ["stella"] }
