[workspace]
authors = ["lee-jin-gyu96 <jin.gyu.lee.96@gmail.com>"]
channels = ["conda-forge"]
name = "MolFinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.7"
pandas = ">=1.3.5,<2"
numpy = ">=1.21.6,<2"
matplotlib = ">=3.3.2,<4"
rdkit = ">=2019.9.3"
